##端口
server:
  port: 9999
##mongo配置




  main:
    allow-bean-definition-overriding: true
  #redis
#mySql
  datasource:
          driver-class-name: com.mysql.jdbc.Driver
          hikari:
              auto-commit: true
              connection-test-query: SELECT 1
              connection-timeout: 30000
              idle-timeout: 30000
              max-lifetime: 1800000
              maximum-pool-size: 15
              minimum-idle: 5
              pool-name: ShangchaoHikariCP
          password: Dwzc_123@
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:mysql://118.190.172.69:3306/shangchao?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
          username: root
  redis:
    database: 0
    host: 118.190.172.69
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
#mybatis
mybatis:
  type-aliases-package: com.shangchao.entity
  mapper-locations: classpath:/mappers/**.xml
shiro:
    redis:
        cacheLive: 30
        cachePrefix: 'shiro_redis_cache:'
        kickoutPrefix: 'shiro_redis_kickout:'
        sessionLive: 30
        sessionPrefix: 'shiro_redis_session:'
#验证码过期5分钟;redis中JWTToken过期时间
redis:
    identifyingTokenExpireTime: 5
    refreshJwtTokenExpireTime: 30
jwt:
    anonymous:
        urls: userLogin,logout,captcha,weChatLogin,webchat,api,swagger,doc,webjars
logging:
  config: classpath:log4j2-spring.xml
webchat:
    webChatAppId: wxc37e18c6dcc427d4
    webChatAppSecret: 468030336ef96c59f63c9f787ea0d97d
    officialAccountsAppId: wx513377a71e122a80
    officialAccountsAppSecret: 66a2f08b3095634532075913c8c9971a